apiVersion: apps/v1
kind: Deployment
metadata:
  name: urbansync-frontend
  namespace: urbansync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: urbansync-frontend
  template:
    metadata:
      labels:
        app: urbansync-frontend
    spec:
      containers:
        - name: frontend
          image: localhost:5000/urbansync-frontend:5e6c200a
          imagePullPolicy: Always
          ports:
            - containerPort: 80
