apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodered
  namespace: urbansync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodered
  template:
    metadata:
      labels:
        app: nodered
    spec:
      containers:
        - name: nodered
          image: nodered/node-red:latest
          ports:
            - containerPort: 1880
          resources:
            requests:
              cpu: "20m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "384Mi"
          volumeMounts:
            - name: nodered-data
              mountPath: /data
      volumes:
        - name: nodered-data
          persistentVolumeClaim:
            claimName: nodered-pvc
