github_pat: ENC[AES256_GCM,data:8B7o+FKhL8hCdIXnVFF6g3IWdDFjp1flNm2ifUsrLF/OhBhSnXVPlQ==,iv:hRY7pWB10OxV04dOugznuDIl7b1QgDokArFTLATrb2o=,tag:Iec5Sq1VzAPtXoulohP9fw==,type:str]
github_username: ENC[AES256_GCM,data:hLzGwXBCAcSr,iv:DVwM5qoDyL6sA+2ptmNyqFyA9HtNKnjteZzwRky3Sqo=,tag:ar+y0tHHBHxzGcmvJXq7rg==,type:str]
jenkins_admin_password: ENC[AES256_GCM,data:Iivqz2xbh6xuQKw=,iv:yv5tO19E4XXIxOU4ssk8PamKnQwAGscd62CQ9m8mSUc=,tag:U6R6ozjpDZdILgqU2LLFng==,type:str]
azure_keyvault_name: ENC[AES256_GCM,data:EZP9cKrEtqH+wGMV,iv:F8D8gyGQTmX6LiOtnLzKCw1xBADb+Olve91o64ZsakM=,tag:JZ33kmuQ9i+UlXPQEWnCxA==,type:str]
azure_tenant_id: ENC[AES256_GCM,data:RsJlpAlt2U0r7i3eP0q9CsyT7pMWb8T5T9jpLQaoXwF9MFLV,iv:7knZOGu9J8kKaad8+KQ83FtmxpzgRDucZ74qSaWL8Hs=,tag:gvzaSveARMsb/qaPp1kFRA==,type:str]
mongo_user: ENC[AES256_GCM,data:JmkdS8Q=,iv:6HZcnPAvxQsZ+ml1PzSFrMjCQZJ7Iel3bnC/oKor2kY=,tag:eIfpR8HFI9HRujOkfY0IgQ==,type:str]
mongo_pass: ENC[AES256_GCM,data:gbUJNdtYJck=,iv:8yCa0p66sZThsop8VY/Z4OgNhyr8UhGEA5lMpwu0MXc=,tag:5EiXWZD2lR47ZWhnGolCrA==,type:str]
mongo_uri: ENC[AES256_GCM,data:rB+3DO2pOovgi6TWVwzGBqNBuUH4ds9nDPnUeCWGx3cKK2yeM6WCJWY4nnnUC2vU/aEs6NKaeKZrpDxzWH9LUI9q,iv:Dhqx8KrWG3ybR0eDa1OOVP9d/R0bkfRikDWdsMK9ZC4=,tag:a20wKlpT3rX6scgRPHjVhA==,type:str]
rabbitmq_user: ENC[AES256_GCM,data:dpHyoBU=,iv:f74Dl9glsfmd1VCo9RoVwLQAxVXcXDCytc+J5HhSZXo=,tag:FycWnCd9iAjlyQd3/NPSOQ==,type:str]
rabbitmq_pass: ENC[AES256_GCM,data:OxhPwUokDu8=,iv:Ej5BO3BvMl/uBe1WOAFBmb0vDuQVqGnXHiNrBZCjsx0=,tag:kRVsPB66t1FLjkK/BfOqsg==,type:str]
rabbitmq_url: ENC[AES256_GCM,data:PgGS2cUxxuE7Ggx181Cu95btBFf6qHnXwIsrNiUoV58A1KQ=,iv:cgaKueTlN1eeKiQaDojgV8n8jFLErzJsDzDp6wQ8uBI=,tag:lANJz7+gTbcuwQttv34pug==,type:str]
minio_access_key: ENC[AES256_GCM,data:LrxQ1gc=,iv:zZVbS4du+DOqJZ34gKlNXdSmznLammVaf3kjA3siNcM=,tag:8dcdAmxfDHkjiPtO1TjAMA==,type:str]
minio_secret_key: ENC[AES256_GCM,data:NuxRGr7dJkiXr2w=,iv:bptzwDV5XYq2iZgas2fm+Ytfo2W+BnumHg19UVBzTOY=,tag:rH86CAYxvRDobk2yp787rQ==,type:str]
jwt_secret: ENC[AES256_GCM,data:iSDFauXoTmjh5OBI/RLC,iv:+qUmqGygAEMjZfx6P5YHMSVwX0Us/ivc7gSHbRh5vJk=,tag:s3tvPf6oU2e0aFWc6WN1Tw==,type:str]
gemini_api_key: ENC[AES256_GCM,data:Q7sQ8tGtDovCmhp0cWgaZD7yXuU6RnjIDSw1/aEKOWMvJih9tQT/E3WlUP0LsWmZ/2h+ZQ==,iv:Vq/dHtOopO0/97BGgVxPplU1n8aEmWaHQleODNmdVCk=,tag:i+ST7mRBs6d5mVp8nUB03w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gv55p0f9e8k6qurz937qe023ccrp7p9ufxnc2zsyuy8ugtqzl4dql8su6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAweWRpNG5kbm1jL3BXWTZ6
            ejBycWhPcjlWOWJVblNXZWpEdEFKUHJTUlJjCjBoSTB5VlpnZ25MQUo4Y1JBL1BZ
            MDlZSVduRThxaVNEcmpPWTNJRG56T2MKLS0tIDlRcm9aSERmZFF6TlRUZHRDUXJ3
            QnJ2VjBnUURCUEExbytVSnp3Smw3cTAKUnVf9rQW1pi8tnepNragQE7pQvCCLaI1
            vY+FrzG8SPzs6ikxpDBkETQEop/bTXfpdmhcnRaR5/NWn1ua4VNglw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-16T19:05:42Z"
    mac: ENC[AES256_GCM,data:tcOV2N9EL6A9mXagTVdOcyV+wE+TjYX1gp9YVfoyS02F7zeXshl2EJUXbK3BGN0c3ZtGxJQ6PHxH45+ALxEU58q7HalKNwHfMeKOLZg5jmQvqH+gorWm3KqKM7yauSTg7kRCKfQF8G32z49GDPoLz06HWJQ+93mY83CPkT5+ifE=,iv:JewWb3fQLVm7AcUmi3aiaOj9oREAH8ce47gryTzvkXo=,tag:PLQlJqk6yrXXe0pmqrd4Rg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
