apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\billx\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f ../docker-compose.yml
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: thingsboard
  name: thingsboard
spec:
  ports:
    - name: "9090"
      port: 9090
      targetPort: 9090
    - name: "1883"
      port: 1883
      targetPort: 1883
    - name: "5683"
      port: 5683
      protocol: UDP
      targetPort: 5683
  selector:
    io.kompose.service: thingsboard
