apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thingsboard-data-pvc
  namespace: urbansync
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thingsboard-logs-pvc
  namespace: urbansync
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
