apiVersion: v1
kind: ConfigMap
metadata:
  name: urbansync-config
  namespace: urbansync
data:
  BACKEND_PORT: "5000"
  CORS_ORIGIN: "http://localhost"
  MINIO_ENDPOINT: "minio"
  MINIO_PORT: "9000"
  MINIO_USE_SSL: "false"
  MINIO_BUCKET: "receipts"
